# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
palette:
  os: "#ACB0BE"
  closer: p:os
  pink: "#F5C2E7"
  lavender: "#B4BEFE"
  blue: "#89B4FA"
blocks:
  - alignment: right
    type: rprompt
    segments:
      - type: python
        style: diamond
        leading_diamond: ""
        # powerline_symbol: 
        fetch_virtual_env: true
        display_default: true
        foreground: "#100e23"
        background: "#FFFFFF"
        template: "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
      - type: kubectl
        background: "#316ce4"
        foreground: "#ffffff"
        leading_diamond: ""
        style: diamond
        template: "󱃾 {{.Context}} "
  - alignment: left
    segments:
      - foreground: "#FEFFEA"
        style: diamond
        background: "#009FB7"
        leading_diamond: 
        trailing_diamond: 
        template: "{{ if .SSHSession }}\ueba9 {{ .UserName }}@{{ .HostName }}{{ end }}"
        type: session
      - foreground: "#FEFFEA"
        properties:
          folder_icon: "...."
          home_icon: "~"
          style: powerlevel
        style: diamond
        trailing_diamond: 
        background: "#009FB7"
        template: " {{ .Path }} "
        type: path
      - background: "#009FB7"
        background_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#52489C{{ end }}"
          - "{{ if gt .Ahead 0 }}#F45B69{{ end }}"
          - "{{ if gt .Behind 0 }}#F45B69{{ end }}"
        foreground: "#FEFFEA"
        powerline_symbol: ""
        properties:
          branch_icon: " "
          commit_icon: " "
          rebase_icon: " "
          revert_icon: " "
          tag_icon: " "
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        style: powerline
        template:
          " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{
          end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed)
          (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{
          end }} "
        type: git
    type: prompt
final_space: true
version: 2
