lua require('szczepad.options')
lua require('szczepad.keymaps')
lua require('szczepad.plugins')
lua require('szczepad.cmp')
lua require('szczepad.lsp')
lua require('szczepad.telescope')
lua require('szczepad.treesitter')
lua require('szczepad.autopairs')
lua require('szczepad.comment')
lua require('szczepad.gitsigns')
lua require('szczepad.nvim-tree')
lua require('szczepad.bufferline')
lua require('szczepad.toggleterm')

colorscheme gruvbox
